### ISSUE TITLE
TLS1.3: Active MITM design vulnerability

### ISSUE THREAD

**Issue by MarkusTeufelberger** [libp2p/specs#208]
Just passing by, I wonder why this comment in #151 hasn't been addressed:

> Unless I'm mistaken, isn't this scheme subject to man-in-the-middle attacks, where one could replace the outer certificate by extracting the inner host key and injecting it into a new certificate produced with a key they control? I'm sure I'm missing something. It seems there is no cryptographic crosslink between the host key and the ephemeral session key.

To me it also seems like the current TLS 1.3 scheme is highly susceptible to active MITM attacks. Usually these are mitigated by having a CA infrastructure around long-lived initial keys, this is obviously not possible here.

Is active MITM out of scope or is there still something planned to address this issue?

**Comment by marten-seemann** [comment]
The ephemeral certificate is signed by the (private) host key:

> The peer signs the concatenation of the string libp2p-tls-handshake: and the public key that it used to generate the certificate carrying the libp2p Public Key Extension, using its private host key. This signature provides cryptographic proof that the peer was in possession of the private host key at the time the certificate was signed. Peers MUST verify the signature, and abort the connection attempt if signature verification fails.

This prevents the MITM attack that you’re describing, doesn't it?

**Comment by MarkusTeufelberger** [comment]
No, it doesn't. A MITM could just forward the valid certificate from either end while being connected to both end points. Then both peers would think they are securely connected, but in practice, they are connected to the MITM.

This violates the "dedicated" part in SECIO:

> Prior to undertaking the SECIO handshake described below, it is assumed that we have already established a **dedicated** bidirectional channel between both parties[...]

**Comment by marten-seemann** [comment]
> No, it doesn't. A MITM could just forward the valid certificate from either end while being connected to both end points.

If that was possible, this would apply to every TLS handshake, not just to libp2p. The reason why this is not possible is that during the TLS handshake the endpoints have to perform a signature using their private key.

**Comment by MarkusTeufelberger** [comment]
It does apply to every TLS handshake, that's why usually you use certificates signed by a trusted CA.

**Comment by marten-seemann** [comment]
The only function that a CA fulfills is verifying that the owner of a public / private key pairs also controls a given domain name. In libp2p, the peer ID is derived from the public key, so we don't need a third party to do this verification for us (in fact, introducing a trusted third party would run against the spirit of building a decentralized network). Every peer can verify if a peer ID matches the key by running a simple cryptographic operation.

**Comment by MarkusTeufelberger** [comment]
You do ephemeral keys on your TLS connections, and don't use the key mentioned in the certificate to encrypt the TLS connection, right? So how do you know you're directly connected to the owner of that key? With certificates, the key mentioned in the certificate is actually used in the handshake...

**Comment by marten-seemann** [comment]
I think I already described that in https://github.com/libp2p/specs/issues/208#issuecomment-522406284.

**Comment by MarkusTeufelberger** [comment]
No. I already wrote that this doesn't prevent an active MITM from forwarding certificates from both ends of a connection. How would you detect this? The certificate IS the one that each party sent and there is nothing in the data exchanged that is tied to the key mentioned in the certificate.

In this scenario, both parties would have the correct key, but be connected via a proxy that can sniff contents on an encrypted channel. Unless libp2p then encrypts contents going over this TLS connection(?), this leads to problems. If you don't care about eavesdropping, youy also could just exchange these certificates in plain though...

**Comment by marten-seemann** [comment]
You can't forward certificates, since [in the TLS handshake](https://tools.ietf.org/html/rfc8446#section-2), the peer signs the handshake with the private key. This signature ties the (outer) certificate to the private key used for generating the signature.

If I understand the attack you're describing correctly, this would be a general attack against any certificate-based TLS handshake, not just against the specific one we're using in libp2p.

**Comment by tomaka** [comment]
Since the certificates are self-signed, you can indeed "man in the middle" by providing a keypair that is different from the one that's normally expected.

This is by design and is a false problem.

Nodes in a peer-to-peer network are equal, so a man in the middle and its target are treated equally. Libp2p decides which `PeerId` each connection corresponds to based on the one that was transmitted during the TLS handshake. If you need to send data to a specific node, at worse you can't reach the node, but you shouldn't be able to send it to the wrong node.

**Comment by MarkusTeufelberger** [comment]
So it is not a problem to have someone impersonate a different peer and connections are designed to be federated, even through TLS? Could very well be the case, if SECIO is also encrypting all the data within the TLS channel.

**Comment by marten-seemann** [comment]
It is not possible to impersonate another peer, that’s what both the SecIO and TLS handshakes make sure.
When using TLS, we’re relying on the ciphersuite negotiated in the handshake, we’re not doing any double encryption.

**Comment by MarkusTeufelberger** [comment]
How do you ensure/verify that you are directly(!) connected to the peer that owns the key pair in the libp2p certificate extension?

**Comment by marten-seemann** [comment]
I'm repeating myself here, but let me try to explain what is written in the spec.

There are two public-private key pairs here:
1. a temporary key
2. the host key

During the TLS handshake, each peer has to perform a signature using its temporary private key. The public key corresponding to that temporary key is contained in the certificate. Furthermore, the certificate also contains the `SignedKey` data structure. This step makes it impossible to just copy the Certificate message, since you can't produce a valid signature for that.

`SignedKey` now contains:
1.  the public key corresponding to the host key
2. A signature performed with the host's private key over the temporary public key

This setup ensures that a peer needs to be in possession of the temporary and the host key to be able to complete a handshake.

**Comment by MarkusTeufelberger** [comment]
Ah, then I misunderstood - I thought the thing that was being signed was the host key, not the temporary (TLS) key.

In that case, this seems secure, yes. Thanks for the clarification!

**Comment by jclab-joseph** [comment]
I also looked at the spec documentation and had the same thought.

https://github.com/libp2p/go-libp2p/blob/3b3605c66690d581950ba539f3e869227e8ba7c0/p2p/security/tls/crypto.go#L184

I checked the mitm safety in the code above.
However, it is difficult to understand this with only the spec document.

**Comment by marten-seemann** [comment]
@jclab-joseph Any suggestion how to improve the spec to make this easier to understand? A PR would be appreciated!
