### ISSUE TITLE
Consider just using public keys for TLS

### ISSUE THREAD

**Issue by DemiMarie-parity** [libp2p/specs#240]
The [current TLS transport spec](https://github.com/libp2p/specs/blob/7467aecfaeeac21eb0c51aec23475f6a4fd5bea7/tls/tls.md) specifies that public keys are encoded in X.509 certificates.  I think we should reconsider this.

Parsing X.509 is highly nontrivial, and is a significant amount of attack surface.  This complexity is just extra overhead in the context of libp2p.  I know that `rustls` just treats certificates as opaque blobs, and I suspect other implementations do as well.  So, if I understand correctly, we can put whatever we want there without causing problems.

**Comment by marten-seemann** [comment]
The TLS RFC [defines](https://tools.ietf.org/html/rfc5246#section-7.4.2) the format for the Certificate extension, and that doesn't allow us to send an opaque blob, even certain implementations don't enforce this.

An alternative would be to use raw public keys ([RFC 7250](https://tools.ietf.org/html/rfc7250)), but we decided against doing this, mainly because none of the TLS implementations we're using offers support for this extension.
