### ISSUE TITLE
Need to be translated into Chinese?

### ISSUE THREAD

**Issue by gguoss** [libp2p/specs#34]
#### This is my translation of ipfs: [ipfs](https: //gguoss.github.io/2017/05/28/ipfs/)

**Comment by mxinden** [comment]
Thanks @gguoss for offering your help. I am closing here for now, given that this issue is rather old. In case you would still like to do a translation, please open up a new issue for this to be further discussed.

**Comment by yellowhunter** [comment]
what？



---Original---
From: "Max ***@***.***&gt;
Date: Sat, Mar 27, 2021 00:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [libp2p/specs] Need to be translated into Chinese? (#34)




 
Thanks @gguoss for offering your help. I am closing here for now, given that this issue is rather old. In case you would still like to do a translation, please open up a new issue for this to be further discussed.

**Comment by yellowhunter** [comment]
？



---Original---
From: "Max ***@***.***&gt;
Date: Sat, Mar 27, 2021 00:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [libp2p/specs] Need to be translated into Chinese? (#34)




 
Closed #34.
