### ISSUE TITLE
multistream: deprecate the simopen extension

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/specs#573]
It looks like the simopen extension to multistream is barely every used in production. I've been running a public Kubo node for an extended amount of time, only running the TCP transport and enabling the Accelerated DHT client, and simopen is exercised not even once per hour. 

This proves out intuition (see https://github.com/libp2p/go-libp2p/issues/2330) that simopen is additional complexity with very little benefit. See that issue for further motivation.

I suggest:
- [x] deprecating the specs here
- [x] removing it from go-libp2p

I don't think any other implementation ever bothered to actually implement it. Is that correct, @mxinden @achingbrain?

**Comment by mxinden** [comment]
I am in favor of deprecating simopen.

> I don't think any other implementation ever bothered to actually implement it. Is that correct, @mxinden @achingbrain?

Implemented, but never merged or released. See https://github.com/libp2p/rust-libp2p/pull/2066.

**Comment by p-shahi** [comment]
Afaik I don't think js-libp2p supports simopen (couldn't find `/libp2p/simultaneous-connect` protocol negotiation string in multistream-select package or elsewhere in the monorepo); @achingbrain can confirm though

**Comment by marten-seemann** [comment]
It's gone! Bye!

**Comment by achingbrain** [comment]
Sorry, missed this - it's not implemented in js-libp2p as @p-shahi found 👍

**Comment by Stebalien** [comment]
This needs to be reverted or we need to stop re-using the inbound the inbound TCP port for outbound connections.

This feature _didn't_ exist to support holepunching, it existed to fix the following:

1. TCP connection drops.
2. TCP connection re-connects _simultaneously_ on both sides.
3. Due to reuseport, we form a single TCP connection (TCP simultaneous connect) and both sides think they're the client.
4. The connection hangs.

We're now experiencing sync issues in lotus where nodes fail to "reconnect" after transient network issues and I'm _guessing_ this is the issue.

**Comment by Stebalien** [comment]
To be clear, the lotus issue may be unrelated. But we definitely didn't introduce this feature to fix NATs.

**Comment by Stebalien** [comment]
Eh, sorry for spamming this issue. I'm moving the conversation to a new issue while we figure out what's going on (https://github.com/libp2p/go-libp2p/issues/2764),

**Comment by marten-seemann** [comment]
Not my business any more, but I'd be surprised if this was the issue.

> 4. The connection hangs.

The connection shouldn't hang. The cryptographic handshake should fail.
